---
title: "connection_tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{connection_tutorial}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(HadesExtras)
options("DEBUG_DATABASECONNECTOR_DBPLYR" = FALSE)
```


```{r}

path_databases_settings_yalm <- "./tests/testthat/config/test_config.yml"

readDatabasesNames(path_databases_settings_yalm)

```

```{r}
database_settings <- readDatabaseSettings(path_databases_settings_yalm, "dev_eunomia")
database_settings <- readDatabaseSettings(path_databases_settings_yalm, "dev_bigquery")
```

```{r}
checkDatabaseSettings(database_settings)
```



```{r}

cdmconnection <- CDMConnectionHandler$new(
  connectionDetails = database_settings$connectionDetails, 
  cdmDatabaseSchema = database_settings$schemas$CDM,
  scracthDatabaseSchema = database_settings$schemas$scratch
  )

```



```{r}

cohortTableObj <- CohortTableHandler$new( 
  cdmConnectionHandler = cdmconnection, cohortTable = "test_cohort_table"
  )

```

# load ids 

```{r}

cohort_data <- tibble::tibble(
    cohort_name = c("cohort 1", "cohort 2"),
    #person_source_value  = c("FG00000001", "FG00000002"),
    person_source_value = c("001f4a87-70d0-435c-a4b9-1425f6928d33", "052d9254-80e8-428f-b8b6-69518b0ef3f3"),
    cohort_start_date = as.Date(c("2020-01-01", "2020-01-01")),
    cohort_end_date = as.Date(c("2020-01-03", "2020-01-04"))
)

appendCohortDataToCohortTable(database_settings, cohort_data)

```




























```{r}


options(DEBUG_DATABASECONNECTOR_DBPLYR=TRUE)

connectionDetails <- Eunomia::getEunomiaConnectionDetails()
connection <- DatabaseConnector::connect(connectionDetails)
#> Connecting using SQLite driver

person_table <- dplyr::tbl(connection,   DatabaseConnector::inDatabaseSchema("main","person"))
visit_occurrence_table <- dplyr::tbl(connection,   DatabaseConnector::inDatabaseSchema("main","visit_occurrence"))



person_table |> 
  dplyr::select(person_source_value, person_id)|>
  dplyr::left_join( visit_occurrence_table |>  dplyr::select(person_id, visit_occurrence_id), by="person_id" ) 
```


```{r}


options(DEBUG_DATABASECONNECTOR_DBPLYR=TRUE)

connection <- DatabaseConnector::connect(database_settings$connectionDetails)
#> Connecting using SQLite driver

person_table <- dplyr::tbl(connection,   DatabaseConnector::inDatabaseSchema("atlas-development-270609:finngen_omop_r11","person"))
visit_occurrence_table <- dplyr::tbl(connection,   DatabaseConnector::inDatabaseSchema("atlas-development-270609:finngen_omop_r11","visit_occurrence"))



person_table |> 
  dplyr::select(person_source_value, person_id)|>
  dplyr::left_join( visit_occurrence_table |>  dplyr::select(person_id, visit_occurrence_id), by="person_id" ) 
```



























