

CohortGenerator_MatchingSubsetQb <- R6::R6Class(
  classname = "MatchingSubsetQb",
  inherit = CohortGenerator:::QueryBuilder,
  private = list(
    innerQuery = function(targetTable) {
      sql <- SqlRender::readSql(system.file("sql", "sql_server", "subsets", "MatchingSubsetOperator.sql", package = "HadesExtras"))
      sql <- SqlRender::render(sql,
                               target_table = targetTable,
                               output_table = self$getTableObjectId(),
                               match_to_cohort_id = private$operator$matchToCohortId,
                               match_ratio = private$operator$matchRatio,
                               match_sex = ifelse(private$operator$matchSex == TRUE, yes = "1", no = "0"),
                               match_birth_year = ifelse(private$operator$matchBirthYear == TRUE, yes = "1", no = "0"),
                               match_start_date_with_in_duration = ifelse(private$operator$matchCohortStartDateWithInDuration == TRUE, yes = "1", no = "0"),
                               new_cohort_start_date_as_match = ifelse(private$operator$newCohortStartDate == "asMatch", yes = "1", no = "0"),
                               new_cohort_end_date_as_match = ifelse(private$operator$newCohortStartDate == "asMatch", yes = "1", no = "0"),
                               warnOnMissingParameters = TRUE
      )
      return(sql)
    }
  )
)

# MatchingSubsetOperator ------------------------------
#' @title Matching Subset Operator
#' @export
#' @description
#' A subset of type cohort - subset a population to only those contained within defined cohort
CohortGenerator_MatchingSubsetOperator <- R6::R6Class(
  classname = "MatchingSubsetOperator",
  inherit = CohortGenerator::SubsetOperator,
  private = list(
    suffixStr = "Match",
    queryBuilder = CohortGenerator_MatchingSubsetQb,
    .matchToCohortId = integer(0),
    .matchRatio = 10,
    .matchSex = TRUE,
    .matchBirthYear = TRUE,
    .matchCohortStartDateWithInDuration = FALSE,
    .newCohortStartDate = "keep",
    .newCohortEndDate = "keep"
  ),
  public = list(
    #' to List
    #' @description List representation of object
    toList = function() {
      objRepr <- super$toList()
      objRepr$matchToCohortId <- private$.matchToCohortId
      objRepr$matchRatio <- private$.matchRatio
      objRepr$matchSex <- private$.matchSex
      objRepr$matchBirthYear <- private$.matchBirthYear
      objRepr$matchCohortStartDateWithInDuration <- private$.matchCohortStartDateWithInDuration
      objRepr$newCohortStartDate <- private$.newCohortStartDate
      objRepr$newCohortEndDate  <- private$.newCohortEndDate

      objRepr
    },
    #' Get auto generated name
    #' @description name generated from subset operation properties
    #'
    #' @return character
    getAutoGeneratedName = function() {
      nameString <- paste0("Match to cohort ", private$.matchToCohortId, " by" )

      matchBy <- as.character()
      if (private$.matchSex) { matchBy <- append(matchBy,"sex") }
      if (private$.matchBirthYear) { matchBy <- append(matchBy,"birth year") }
      if (private$.matchCohortStartDateWithInDuration) { matchBy <- append(matchBy,"cohort start date within cohort duration") }

      nameString <- paste(nameString, paste(matchBy, collapse = " and "))

      nameString <- paste0(nameString, " with ratio 1:", private$.matchRatio)
      if (private$.newCohortStartDate == "asMatch") {
        nameString <- paste0(nameString, "; cohort start date as in matched subject")
      }
      if (private$.newCohortEndDate == "asMatch" ) {
        nameString <- paste0(nameString, "; cohort end date as in matched subject")
      }

      return(paste0(nameString))
    }
  ),
  active = list(
    #' @field matchToCohortId Integer id of cohorts to match to
    matchToCohortId = function(matchToCohortId) {
      if (missing(matchToCohortId)) {
        return(private$.matchToCohortId)
      }

      matchToCohortId <- as.integer(matchToCohortId)
      checkmate::assertIntegerish(matchToCohortId, len = 1)
      checkmate::assertFALSE(any(is.na(matchToCohortId)))
      private$.matchToCohortId <- matchToCohortId
      self
    },
    #' @field matchRatio matching ratio
    matchRatio = function(matchRatio) {
      if (missing(matchRatio)) {
        return(private$.matchRatio)
      }

      checkmate::assertIntegerish(matchRatio, len = 1)
      private$.matchRatio <- matchRatio
      self
    },
    #' @field matchSex match to target sex
    matchSex = function(matchSex) {
      if (missing(matchSex)) {
        return(private$.matchSex)
      }

      checkmate::assertLogical(matchSex, len = 1)
      private$.matchSex <- matchSex
      self
    },
    #' @field matchBirthYear match to target birth year
    matchBirthYear = function(matchBirthYear) {
      if (missing(matchBirthYear)) {
        return(private$.matchBirthYear)
      }

      checkmate::assertLogical(matchBirthYear, len = 1)
      private$.matchBirthYear <- matchBirthYear
      self
    },
    #' @field matchCohortStartDateWithInDuration match have start date as in cohort duration
    matchCohortStartDateWithInDuration = function(matchCohortStartDateWithInDuration) {
      if (missing(matchCohortStartDateWithInDuration)) {
        return(private$.matchCohortStartDateWithInDuration)
      }

      checkmate::assertLogical(matchCohortStartDateWithInDuration, len = 1)
      private$.matchCohortStartDateWithInDuration <- matchCohortStartDateWithInDuration
      self
    },
    #' @field newCohortStartDate change cohort start date to the matched person
    newCohortStartDate = function(newCohortStartDate) {
      if (missing(newCohortStartDate)) {
        return(private$.newCohortStartDate)
      }

      checkmate::assertChoice(x = newCohortStartDate, choices = c("keep", "asMatch"))
      private$.newCohortStartDate <- newCohortStartDate
      self
    },
    #' @field newCohortEndDate  change cohort end date to the matched person
    newCohortEndDate  = function(newCohortEndDate ) {
      if (missing(newCohortEndDate )) {
        return(private$.newCohortEndDate )
      }

      checkmate::assertChoice(x = newCohortEndDate, choices = c("keep", "asMatch"))
      private$.newCohortEndDate  <- newCohortEndDate
      self
    }
  )
)

# createMatchingSubset ------------------------------
#' A definition of subset functions to be applied to a set of cohorts
#' @export
#'
#' @param name  optional name of operator
#' @param matchToCohortId integer - cohort ids to match to
#' @param matchSex match to target sex
#' @param matchBirthYear match to target birth year
#' @param matchRatio matching ratio
#' @param newCohortStartDate change cohort start date to the matched person
#' @param newCohortEndDate  change cohort end date to the matched person
#'
#' @returns a MatchingSubsetOperator instance
createMatchingSubset <- function(
    name = NULL,
    matchToCohortId,
    matchRatio = 10,
    matchSex = TRUE,
    matchBirthYear = TRUE,
    matchCohortStartDateWithInDuration = FALSE,
    newCohortStartDate = "keep",
    newCohortEndDate = "keep") {

  if(!matchSex & !matchBirthYear){
    stop("Either matchSex or matchBirthYear has to be chosen, both cannot be FALSE")
  }

  subset <- CohortGenerator_MatchingSubsetOperator$new()
  subset$name <- name
  subset$matchToCohortId <- matchToCohortId
  subset$matchRatio <- matchRatio
  subset$matchSex <- matchSex
  subset$matchCohortStartDateWithInDuration <- matchCohortStartDateWithInDuration
  subset$matchBirthYear <- matchBirthYear
  subset$newCohortStartDate <- newCohortStartDate
  subset$newCohortEndDate <- newCohortEndDate

  subset
}

